[project]
name = "computer-computer"
dynamic = ["version"]
dependencies = ["numpy", "pydantic", "scipy"]
# Keep in sync with pyodide version
requires-python = "==3.12.7"

[project.optional-dependencies]
dev = ["mypy", "pytest", "ruff", "scipy-stubs"]

[build-system]
requires = ["hatchling", "hatch-nodejs-version"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "nodejs"
path = "../package.json"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
log_cli_level = "INFO"
testpaths = ["tests"]

[tool.ruff]
line-length = 100
output-format = "full"

[tool.ruff.lint]
extend-select = [
  "D",   # pydocstring
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort
  "UP",  # pyupgrade
  "W",   # pycodestyle warnings
  "NPY", # numpy-specific
]

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]
